name: Build SDA C-5 Community App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v4
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build AAB
      run: flutter build appbundle --release
      
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: sda-c5-community-app-bundle
        path: build/app/outputs/bundle/release/app-release.aab
        
    - name: Build APK for testing
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sda-c5-community-app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/bundle/release/app-release.aab
          build/app/outputs/flutter-apk/app-release.apk
        tag_name: v${{ github.run_number }}
        name: SDA C-5 Community App v${{ github.run_number }}
        body: |
          ## SDA C-5 Community App
          
          ### What's Changed
          - Updated with latest changes
          - Fixed internet permissions for daily reading functionality
          
          ### Downloads
          - **AAB Bundle**: For Google Play Store upload
          - **APK**: For direct installation and testing
          
          ### Features
          - Daily Bible readings
          - Prayer requests
          - Church announcements
          - Live streaming
          - Donations
          - Events calendar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 